### ISSUE TITLE
printing stops randomly

### ISSUE THREAD

**Issue by droptic** [CrealityOfficial/Creality_Sonic_Pad#50]
klippy.log show this

[ERROR] 2023-06-03 18:04:39,214 [root] [virtual_sdcard:_load_file:251] File opened:ender3v2/PowerShroudModUpdatedV2_2h25m_0.20mm_200C_PLA_ENDER3S1.gcode Size:800886 start_print
[ERROR] 2023-06-03 18:04:39,775 [root] [virtual_sdcard:work_handler:453] 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/share/klipper/klippy/extras/virtual_sdcard.py", line 431, in work_handler
    timelapse_postion = int(config_data.get('1').get("position", 0))
AttributeError: 'NoneType' object has no attribute 'get'
[ERROR] 2023-06-03 18:07:11,385 [root] [__init__:logging_callback:267] Got EOF when reading from device
[ERROR] 2023-06-03 18:07:15,908 [root] [klippy:invoke_shutdown:365] Transition to shutdown state: Lost communication with MCU 'mcu'
[ERROR] 2023-06-03 18:07:15,947 [root] [virtual_sdcard:work_handler:798] filename:/root/gcode_files/ender3v2/PowerShroudModUpdatedV2_2h25m_0.20mm_200C_PLA_ENDER3S1.gcode end print
[ERROR] 2023-06-03 18:16:16,088 [root] [virtual_sdcard:_load_file:251] File opened:ender3v2/PowerShroudModUpdatedV2_2h25m_0.20mm_200C_PLA_ENDER3S1.gcode Size:800886 start_print
[ERROR] 2023-06-03 18:16:16,659 [root] [virtual_sdcard:work_handler:453] 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/share/klipper/klippy/extras/virtual_sdcard.py", line 431, in work_handler
    timelapse_postion = int(config_data.get('1').get("position", 0))
AttributeError: 'NoneType' object has no attribute 'get'
[ERROR] 2023-06-03 18:18:11,316 [root] [virtual_sdcard:work_handler:798] filename:/root/gcode_files/ender3v2/PowerShroudModUpdatedV2_2h25m_0.20mm_200C_PLA_ENDER3S1.gcode end print
[ERROR] 2023-06-03 18:22:36,852 [root] [virtual_sdcard:_load_file:251] File opened:U_PowerShroudModUpdatedV2_2h25m_0.20mm_200C_PLA_ENDER3S1.gcode Size:800886 start_print
[ERROR] 2023-06-03 18:22:37,474 [root] [virtual_sdcard:work_handler:453] 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/share/klipper/klippy/extras/virtual_sdcard.py", line 431, in work_handler
    timelapse_postion = int(config_data.get('1').get("position", 0))
AttributeError: 'NoneType' object has no attribute 'get'

I restored the settings to the factory settings but I still have the same problem and I can't print anything

**Comment by droptic** [comment]
this problem occurs with large gcode files > 10 mb and this occurs with both internal and usb memory
