### ISSUE TITLE
Moonraker dependency Apprise

### ISSUE THREAD

**Issue by leafeven** [CrealityOfficial/Creality_Sonic_Pad#63]
Moonraker dependency apprise is not available, preventing use of notifier feature of moonraker

moonraker.conf
```
[notifier pushover_notifier]
url: pover://{user_key}@{token}
events: gcode
title: Printer Message
body: {event_message}
attach: http://localhost:8080/?action=snapshot
```

from moonraker.log
```python
[ERROR] 2023-07-02 12:28:13,530 [root] [server:load_component:283] Unable to load component: (notifier)
Traceback (most recent call last):
  File "/usr/share/moonraker/moonraker/server.py", line 275, in load_component
    module = importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/moonraker/moonraker/components/notifier.py", line 9, in <module>
    import apprise
ModuleNotFoundError: No module named 'apprise'
```

System Version V1.0.6.49.145

**Comment by Creality-Ralf** [comment]
We are not yet integrated and plan to do so in August. Currently you can install via pip install apprise
